# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58b4ad083a7b530456e9ebed6865382d5d837856c28fc0b4452732bc57479b303346708c06e2da523850c9994a95c6e8078c99ec3a389fa08c2d554598e2415f

test:
  secret_key_base: 5431df9316c0eae94b6057810144d930481f9a65a2bbc856d409b3b391844d5082228a066c3592828ac564a27246046716fb5d8f0c5559867787ae8f808fd7ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
